repos:
  - repo: local
    hooks:
      -  id: nixpkgs-fmt
         name: nixpkgs-fmt
         description: Format nix code with nixpkgs-fmt.
         entry: nixpkgs-fmt
         files: \.nix$
         language: system
         minimum_pre_commit_version: 1.18.1
